from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.home,name='Home'),
    path('student_login/',views.studentlogin,name='studentlogin'),
    path('admin_login/',views.adminlogin,name='adminlogin'),
    path('student_register/',views.studentregister,name='studentregister'),
    path('Godavari_hostel/', views.godavari, name='godavari'),
    path('krishna_hostel/', views.krishna, name='krishna'),
    path('Saraswathi_hostel/', views.saraswathi, name='saraswathi'),
    path('Sharadha_hostel/', views.sharadha, name='sharadha'),
    path('contactus/',views.contact_us,name='contactus'),
    path('logout/', views.logoutUser, name="logout"),
    path('add_caretaker/',views.AddCaretaker,name='AddCaretaker'),
    path('add_HM/',views.AddHM,name='AddHM'),
    path('HM_home/',views.HMhome,name='HMhome'),
    path('caretaker_home/',views.caretakerhome,name='caretakerhome'),
    path('student_home/',views.studenthome,name='studenthome'),
    path('student_profile/',views.studentprofile,name='studentprofile'),
    path('student_update_profile/',views.studentupdateprofile,name='studentupdateprofile'),
    path('student_pending_requests/',views.studentpendingrequests,name='studentpendingrequests'),
    path('student_approved_requests/', views.studentapprovedrequests, name='studentapprovedrequests'),
    path('student_active_requests/', views.studentactiverequests, name='studentactiverequests'),
    path('student_past_records/', views.studentpastrequests, name='studentpastrequests'),
    path('student_rejected_requests/',views.studentrejectedrequests,name='studentrejectedrequests'),
    path('delete_request/<str:pk>/',views.deleterequest,name='deleterequest'),
    path('student_instructions/', views.studentinstructions, name='studentinstructions'),
    path('caretaker_profile/',views.caretakerprofile,name='caretakerprofile'),
    path('caretaker_approved_requests/',views.crapprovedrequests,name='crapprovedrequests'),
    path('caretaker_lefttoday/',views.crlefttoday,name='crlefttoday'),
    path('caretaker_arrivedtoday/', views.crarrivedtoday, name='crarrivedtoday'),
    path('caretaker_studentstatus/', views.crknowstudentstatus, name='crstudentstatus'),
    path('caretaker_on_day_out/',views.crondayout,name='activedayout'),
    path('caretaker_instructions/', views.crinstructions, name='crinstructions'),
    path('review_request/<str:pk>/',views.viewrequest,name='viewrequest'),
    path('caretaker_update_profile/',views.caretakerupdateprofile,name='caretakerupdateprofile'),
    path('HM_profile/',views.HMprofile,name='HMprofile'),
    path('HM_update_profile/', views.HMupdateprofile, name='HMupdateprofile'),
    path('HM_approved_requests/',views.hmapprovedrequests,name='hmapprovedrequests'),
    path('HM_student_status/', views.hmknowstudentstatus, name='hmstudentstatus'),
    path('HM_instructions/', views.HMinstructions, name='hminstructions'),
    path('securitylogin/',views.securitylogin,name='securitylogin'),
    path('securityhome/',views.securityhome,name='securityhome'),
    path('security_check/<str:pk>',views.securitycheck,name='securitycheck'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="Home/password_reset.html"),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="Home/password_reset_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="Home/password_reset_form.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="Home/password_reset_done.html"),name="password_reset_complete"),
]