# Generated by Django 3.0.8 on 2020-07-21 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('HM', 'Hostel Manager'), ('Caretaker', 'Caretaker'), ('maintainance', 'Maintainance')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[('Godavari', 'Godavari Boys Hostel'), ('krishna', 'Krishna Boys Hostel'), ('sharadha', 'Sharadha Girls Hostel'), ('saraswathi', 'Saraswathi Girls Hostel')], max_length=200, null=True),
        ),
    ]
