# Generated by Django 3.0.8 on 2020-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20200722_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
