# Generated by Django 3.0.8 on 2020-07-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20200723_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Staff'),
        ),
    ]
