# Generated by Django 3.0.8 on 2020-07-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20200723_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='staff',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
