# Generated by Django 3.0.8 on 2020-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20200723_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='in_date',
            field=models.DateField(error_messages={'required': 'Enter in date-month-year format'}, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='in_time',
            field=models.TimeField(error_messages={'required': 'Enter in hour:mintues am/pm format'}, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='out_date',
            field=models.DateField(error_messages={'required': 'Enter in date-month-year format'}, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='out_time',
            field=models.TimeField(error_messages={'required': 'Enter in hour:mintues am/pm format'}, null=True),
        ),
    ]
