# Generated by Django 3.0.8 on 2020-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_auto_20200723_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Specify correct address', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='in_date',
            field=models.DateField(error_messages={'validationerror': 'Enter in date-month-year format'}, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='in_time',
            field=models.TimeField(error_messages={'validationerror': 'Enter in hour:mintues am/pm format'}, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='out_date',
            field=models.DateField(error_messages={'validationerror': 'Enter in date-month-year format'}, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='out_time',
            field=models.TimeField(error_messages={'validationerror': 'Enter in hour:mintues am/pm format'}, null=True),
        ),
    ]
