# Generated by Django 3.0.8 on 2020-07-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_remove_appeal_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='roomno',
            new_name='room_no',
        ),
    ]
