# Generated by Django 3.0.8 on 2020-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_auto_20200723_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='in_datetime',
            field=models.DateTimeField(verbose_name='In Date&Time(yyyy/mm/dd 24:60)'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='out_datetime',
            field=models.DateTimeField(verbose_name='Out Date&Time (yyyy/mm/dd 24:60)'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='type',
            field=models.CharField(choices=[('home-out', 'Home-Out'), ('day-out', 'Day-Out')], default='home-out', max_length=200),
        ),
    ]
