# Generated by Django 3.0.8 on 2020-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_auto_20200727_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='father_mobile_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
