# Generated by Django 3.0.8 on 2020-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0039_auto_20200729_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('In', 'Inside Hostel'), ('Out', 'Outside Hostel')], default='In', max_length=200, null=True),
        ),
    ]
