# Generated by Django 3.0.8 on 2020-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=200, null=True),
        ),
    ]
