# Generated by Django 3.0.8 on 2020-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_staff_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hostel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
