# Generated by Django 3.0.8 on 2020-07-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200721_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fmobileno',
            new_name='fathermobileno',
        ),
    ]
