# Generated by Django 3.0.8 on 2020-07-23 06:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20200722_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('In', 'Inside Hostel'), ('Out', 'Outside Hostel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home-out', 'Home-Out'), ('day-out', 'Day-Out')], max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('roomno', models.IntegerField(null=True)),
                ('out_time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('used', 'Used')], max_length=200, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Staff')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Student')),
            ],
        ),
    ]
