# Generated by Django 3.0.8 on 2020-07-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_auto_20200723_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='address',
        ),
    ]
