# Generated by Django 3.0.8 on 2020-07-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_appeal_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='hostel',
            field=models.CharField(choices=[('Godavari', 'Godavari Boys Hostel'), ('krishna', 'Krishna Boys Hostel'), ('sharadha', 'Sharadha Girls Hostel'), ('saraswathi', 'Saraswathi Girls Hostel')], max_length=100, null=True),
        ),
    ]
