# Generated by Django 3.0.8 on 2020-07-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_appeal_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=200, null=True),
        ),
    ]
