# Generated by Django 3.0.8 on 2020-07-29 16:03

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0038_auto_20200729_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='default.png', null=True, upload_to='profilepics', validators=[Home.models.validate_image]),
        ),
    ]
