# Generated by Django 3.0.8 on 2020-08-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0043_auto_20200801_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('ECE', 'ECE')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('I-M.tech', 'I-M.tech'), ('II-M.tech', 'II-M.tech')], max_length=200, null=True),
        ),
    ]
