# Generated by Django 3.0.8 on 2020-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0044_auto_20200802_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='timings',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
